name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    # Use your own writable database (create it in Snowflake if not exists)
    +database: DBT_MFARID         # Change this if you use a different dev DB
    +schema: dbt_mfarid           # Default schema for misc models

    silver:
      +schema: dbt_mfarid_silver  # All silver-layer models go here
      +materialized: view         # Light transforms usually as views

    gold:
      +schema: dbt_mfarid_gold    # All gold-layer models go here
      +materialized: table        # Aggregations stored as tables
